devicetree:
  dtbo-method: libufdt
  overlays:
    pca9685:
      enabled: true
      params:
        i2c: i2c0
    rk628d:
      enabled: false
      params:
        i2c: i2c2
        csi: csi0
        lanes: 2
        i2s: i2s1
    gpio-ir-tx-overlay:
      enabled: true
      params:
        gpio: GPIOH_0
    ramoops:
      enabled: true

loaders:
  archlinuxarm:
    title: Archlinux ARM with Universal Mainline Kernel
    type: linux-efi
    kernel: /vmlinuz-linux-mainline-aarch64
    initramfs:
    - /initramfs-linux-mainline-aarch64.img
    bootargs:
    - loglevel=7
    - panic=30
    ktype: mainline
  test-item0:
    title: Test Item 0
    type: reboot
  test-item1:
    title: Test Item 1
    type: reboot
  test-item2:
    title: Test Item 2
    type: reboot
  test-item3:
    title: Test Item 3
    type: reboot
  test-item4:
    title: Test Item 4
    type: reboot
  test-item5:
    title: Test Item 5
    type: reboot
  test-item6:
    title: Test Item 6
    type: reboot
  test-item7:
    title: Test Item 7
    type: reboot
  test-item8:
    title: Test Item 8
    type: reboot
  test-item9:
    title: Test Item 9
    type: reboot
  test-item10:
    title: Test Item 10
    type: reboot
  test-item11:
    title: Test Item 11
    type: reboot
  test-item12:
    title: Test Item 12
    type: reboot
  test-item13:
    title: Test Item 13
    type: reboot
  test-item14:
    title: Test Item 14
    type: reboot
  test-item15:
    title: Test Item 15
    type: reboot
  test-item16:
    title: Test Item 16
    type: reboot
  test-item17:
    title: Test Item 17
    type: reboot
  test-item18:
    title: Test Item 18
    type: reboot
  test-item19:
    title: Test Item 19
    type: reboot
  test-item20:
    title: Test Item 20
    type: reboot
  test-item21:
    title: Test Item 21
    type: reboot
  test-item22:
    title: Test Item 22
    type: reboot
  test-item23:
    title: Test Item 23
    type: reboot
  test-item24:
    title: Test Item 24
    type: reboot
  test-item25:
    title: Test Item 25
    type: reboot
  test-item26:
    title: Test Item 26
    type: reboot
  test-item27:
    title: Test Item 27
    type: reboot
  test-item28:
    title: Test Item 28
    type: reboot
  test-item29:
    title: Test Item 29
    type: reboot
  test-item30:
    title: Test Item 30
    type: reboot
  test-item31:
    title: Test Item 31
    type: reboot
  test-item32:
    title: Test Item 32
    type: reboot
  test-item33:
    title: Test Item 33
    type: reboot
  test-item34:
    title: Test Item 34
    type: reboot
  test-item35:
    title: Test Item 35
    type: reboot
  test-item36:
    title: Test Item 36
    type: reboot
  test-item37:
    title: Test Item 37
    type: reboot
  test-item38:
    title: Test Item 38
    type: reboot
  test-item39:
    title: Test Item 39
    type: reboot
  test-item40:
    title: Test Item 40
    type: reboot
  test-item41:
    title: Test Item 41
    type: reboot
  test-item42:
    title: Test Item 42
    type: reboot
  test-item43:
    title: Test Item 43
    type: reboot
  test-item44:
    title: Test Item 44
    type: reboot
  test-item45:
    title: Test Item 45
    type: reboot
  test-item46:
    title: Test Item 46
    type: reboot
  test-item47:
    title: Test Item 47
    type: reboot
  test-item48:
    title: Test Item 48
    type: reboot
  test-item49:
    title: Test Item 49
    type: reboot
  