devicetree:
  dtbo-method: libufdt
  overlays:
    pca9685:
      enabled: true
      params:
        i2c: i2c0
    rk628d:
      enabled: false
      params:
        i2c: i2c2
        csi: csi0
        lanes: 2
        i2s: i2s1
    gpio-ir-tx-overlay:
      enabled: true
      params:
        gpio: GPIOH_0
    ramoops:
      enabled: true

loaders:
  archlinuxarm:
    title: Archlinux ARM with Universal Mainline Kernel
    type: linux-efi
    kernel: /vmlinuz-linux-mainline-aarch64
    initramfs:
    - /initramfs-linux-mainline-aarch64.img
    bootargs:
    - loglevel=7
    - panic=30
    ktype: mainline
