#include "../smbios.h"

static const char *processor_type_to_string(int v) {
	switch (v) {
		case 0x01: return "other";
		case 0x02: return "unknown";
		case 0x03: return "central_processor";
		case 0x04: return "math_processor";
		case 0x05: return "dsp_processor";
		case 0x06: return "video_processor";
		default: return "reserved";
	}
}

static const char *processor_family_to_string(int v) {
	switch (v) {
		case 0x01: return "other";
		case 0x02: return "unknown";
		case 0x03: return "8086";
		case 0x04: return "80286";
		case 0x05: return "intel386";
		case 0x06: return "intel486";
		case 0x07: return "8087";
		case 0x08: return "80287";
		case 0x09: return "80387";
		case 0x0A: return "80487";
		case 0x0B: return "pentium";
		case 0x0C: return "pentium_pro";
		case 0x0D: return "pentium_ii";
		case 0x0E: return "pentium_mmx";
		case 0x0F: return "celeron";
		case 0x10: return "pentium_ii_xeon";
		case 0x11: return "pentium_iii";
		case 0x12: return "m1";
		case 0x13: return "m2";
		case 0x14: return "intel_celeron_m";
		case 0x15: return "intel_pentium4_ht";
		case 0x16: return "intel";
		case 0x18: return "amd_duron";
		case 0x19: return "k5";
		case 0x1A: return "k6";
		case 0x1B: return "k6_2";
		case 0x1C: return "k6_3";
		case 0x1D: return "amd_athlon";
		case 0x1E: return "amd29000";
		case 0x1F: return "k6_2_plus";
		case 0x20: return "power_pc";
		case 0x21: return "power_pc601";
		case 0x22: return "power_pc603";
		case 0x23: return "power_pc603_plus";
		case 0x24: return "power_pc604";
		case 0x25: return "power_pc620";
		case 0x26: return "power_p_cx704";
		case 0x27: return "power_pc750";
		case 0x28: return "intel_core_duo";
		case 0x29: return "intel_core_duo_mobile";
		case 0x2A: return "intel_core_solo_mobile";
		case 0x2B: return "intel_atom";
		case 0x2C: return "intel_core_m";
		case 0x2D: return "intel_corem3";
		case 0x2E: return "intel_corem5";
		case 0x2F: return "intel_corem7";
		case 0x30: return "alpha";
		case 0x31: return "alpha21064";
		case 0x32: return "alpha21066";
		case 0x33: return "alpha21164";
		case 0x34: return "alpha21164pc";
		case 0x35: return "alpha21164a";
		case 0x36: return "alpha21264";
		case 0x37: return "alpha21364";
		case 0x38: return "amd_turion_ii_ultra_dual_core_mobile_m";
		case 0x39: return "amd_turion_ii_dual_core_mobile_m";
		case 0x3A: return "amd_athlon_ii_dual_core_m";
		case 0x3B: return "amd_opteron6100_series";
		case 0x3C: return "amd_opteron4100_series";
		case 0x3D: return "amd_opteron6200_series";
		case 0x3E: return "amd_opteron4200_series";
		case 0x3F: return "amd_fx_series";
		case 0x40: return "mips";
		case 0x41: return "mipsr4000";
		case 0x42: return "mipsr4200";
		case 0x43: return "mipsr4400";
		case 0x44: return "mipsr4600";
		case 0x45: return "mipsr10000";
		case 0x46: return "amd_c_series";
		case 0x47: return "amd_e_series";
		case 0x48: return "amd_a_series";
		case 0x49: return "amd_g_series";
		case 0x4A: return "amd_z_series";
		case 0x4B: return "amd_r_series";
		case 0x4C: return "amd_opteron4300";
		case 0x4D: return "amd_opteron6300";
		case 0x4E: return "amd_opteron3300";
		case 0x4F: return "amd_fire_pro_series";
		case 0x50: return "sparc";
		case 0x51: return "super_sparc";
		case 0x52: return "micro_sparc_ii";
		case 0x53: return "micro_sparc_i_iep";
		case 0x54: return "ultra_sparc";
		case 0x55: return "ultra_sparc_ii";
		case 0x56: return "ultra_sparc_iii";
		case 0x57: return "ultra_sparc_iii";
		case 0x58: return "ultra_sparc_ii_ii";
		case 0x60: return "68040";
		case 0x61: return "68xxx";
		case 0x62: return "68000";
		case 0x63: return "68010";
		case 0x64: return "68020";
		case 0x65: return "68030";
		case 0x66: return "amd_athlon_x4_quad_core";
		case 0x67: return "amd_opteron_x1000_series";
		case 0x68: return "amd_opteron_x2000_series";
		case 0x69: return "amd_opteron_a_series";
		case 0x6A: return "amd_opteron_x3000_series";
		case 0x6B: return "amd_zen";
		case 0x70: return "hobbit";
		case 0x78: return "crusoe_tm5000";
		case 0x79: return "crusoe_tm3000";
		case 0x7A: return "efficeon_tm8000";
		case 0x80: return "weitek";
		case 0x82: return "itanium";
		case 0x83: return "amd_athlon64";
		case 0x84: return "amd_opteron";
		case 0x85: return "amd_sempron";
		case 0x86: return "amd_turion64_mobile";
		case 0x87: return "dual_core_amd_opteron";
		case 0x88: return "amd_athlon64x2_dual_core";
		case 0x89: return "amd_turion64x2_mobile";
		case 0x8A: return "quad_core_amd_opteron";
		case 0x8B: return "third_generation_amd_opteron";
		case 0x8C: return "amd_phenom_fx_quad_core";
		case 0x8D: return "amd_phenom_x4_quad_core";
		case 0x8E: return "amd_phenom_x2_dual_core";
		case 0x8F: return "amd_athlon_x2_dual_core";
		case 0x90: return "parisc";
		case 0x91: return "pa_risc8500";
		case 0x92: return "pa_risc8000";
		case 0x93: return "pa_risc7300lc";
		case 0x94: return "pa_risc7200";
		case 0x95: return "pa_risc7100lc";
		case 0x96: return "pa_risc7100";
		case 0xA0: return "v30";
		case 0xA1: return "quad_core_intel_xeon3200_series";
		case 0xA2: return "dual_core_intel_xeon3000_series";
		case 0xA3: return "quad_core_intel_xeon5300_series";
		case 0xA4: return "dual_core_intel_xeon5100_series";
		case 0xA5: return "dual_core_intel_xeon5000_series";
		case 0xA6: return "dual_core_intel_xeon_lv";
		case 0xA7: return "dual_core_intel_xeon_ulv";
		case 0xA8: return "dual_core_intel_xeon7100_series";
		case 0xA9: return "quad_core_intel_xeon5400_series";
		case 0xAA: return "quad_core_intel_xeon";
		case 0xAB: return "dual_core_intel_xeon5200_series";
		case 0xAC: return "dual_core_intel_xeon7200_series";
		case 0xAD: return "quad_core_intel_xeon7300_series";
		case 0xAE: return "quad_core_intel_xeon7400_series";
		case 0xAF: return "multi_core_intel_xeon7400_series";
		case 0xB0: return "pentium_iii_xeon";
		case 0xB1: return "pentium_iii_speed_step";
		case 0xB2: return "pentium4";
		case 0xB3: return "intel_xeon";
		case 0xB4: return "as400";
		case 0xB5: return "intel_xeon_mp";
		case 0xB6: return "amd_athlon_xp";
		case 0xB7: return "amd_athlon_mp";
		case 0xB8: return "intel_itanium2";
		case 0xB9: return "intel_pentium_m";
		case 0xBA: return "intel_celeron_d";
		case 0xBB: return "intel_pentium_d";
		case 0xBC: return "intel_pentium_ex";
		case 0xBD: return "intel_core_solo";
		case 0xBE: return "reserved";
		case 0xBF: return "intel_core2";
		case 0xC0: return "intel_core2_solo";
		case 0xC1: return "intel_core2_extreme";
		case 0xC2: return "intel_core2_quad";
		case 0xC3: return "intel_core2_extreme_mobile";
		case 0xC4: return "intel_core2_duo_mobile";
		case 0xC5: return "intel_core2_solo_mobile";
		case 0xC6: return "intel_core_i7";
		case 0xC7: return "dual_core_intel_celeron";
		case 0xC8: return "ibm390";
		case 0xC9: return "g4";
		case 0xCA: return "g5";
		case 0xCB: return "g6";
		case 0xCC: return "z_architecture";
		case 0xCD: return "intel_core_i5";
		case 0xCE: return "intel_core_i3";
		case 0xCF: return "intel_core_i9";
		case 0xD0: return "intel_xeon_d";
		case 0xD2: return "via_c7m";
		case 0xD3: return "via_c7d";
		case 0xD4: return "via_c7";
		case 0xD5: return "via_eden";
		case 0xD6: return "multi_core_intel_xeon";
		case 0xD7: return "dual_core_intel_xeon3_series";
		case 0xD8: return "quad_core_intel_xeon3_series";
		case 0xD9: return "via_nano";
		case 0xDA: return "dual_core_intel_xeon5_series";
		case 0xDB: return "quad_core_intel_xeon5_series";
		case 0xDD: return "dual_core_intel_xeon7_series";
		case 0xDE: return "quad_core_intel_xeon7_series";
		case 0xDF: return "multi_core_intel_xeon7_series";
		case 0xE0: return "multi_core_intel_xeon3400_series";
		case 0xE4: return "amd_opteron3000_series";
		case 0xE5: return "amd_sempron_ii";
		case 0xE6: return "embedded_amd_opteron_quad_core";
		case 0xE7: return "amd_phenom_triple_core";
		case 0xE8: return "amd_turion_ultra_dual_core_mobile";
		case 0xE9: return "amd_turion_dual_core_mobile";
		case 0xEA: return "amd_athlon_dual_core";
		case 0xEB: return "amd_sempron_si";
		case 0xEC: return "amd_phenom_ii";
		case 0xED: return "amd_athlon_ii";
		case 0xEE: return "six_core_amd_opteron";
		case 0xEF: return "amd_sempron_m";
		case 0xFA: return "i860";
		case 0xFB: return "i960";
		default: return "reserved";
	}
}
static const char *processor_family2_to_string(int v) {
	switch (v) {
		case 0x0100: return "armv7";
		case 0x0101: return "armv8";
		case 0x0102: return "armv9";
		case 0x0104: return "sh3";
		case 0x0105: return "sh4";
		case 0x0118: return "arm";
		case 0x0119: return "strongarm";
		case 0x012C: return "6x86";
		case 0x012D: return "media_gx";
		case 0x012E: return "mii";
		case 0x0140: return "win_chip";
		case 0x015E: return "dsp";
		case 0x01F4: return "video_processor";
		case 0x0200: return "riscv_rv32";
		case 0x0201: return "riscv_rv64";
		case 0x0202: return "riscv_rv128";
		case 0x0258: return "loongarch";
		case 0x0259: return "loongson1";
		case 0x025A: return "loongson2";
		case 0x025B: return "loongson3";
		case 0x025C: return "loongson2k";
		case 0x025D: return "loongson3a";
		case 0x025E: return "loongson3b";
		case 0x025F: return "loongson3c";
		case 0x0260: return "loongson3d";
		case 0x0261: return "loongson3e";
		case 0x0262: return "dual_core_loongson2k";
		case 0x026C: return "quad_core_loongson3a";
		case 0x026D: return "multi_core_loongson3a";
		case 0x026E: return "quad_core_loongson3b";
		case 0x026F: return "multi_core_loongson3b";
		case 0x0270: return "multi_core_loongson3c";
		case 0x0271: return "multi_core_loongson3d";
		case 0x0300: return "intel_core3";
		case 0x0301: return "intel_core5";
		case 0x0302: return "intel_core7";
		case 0x0303: return "intel_core9";
		case 0x0304: return "intel_core_ultra3";
		case 0x0305: return "intel_core_ultra5";
		case 0x0306: return "intel_core_ultra7";
		case 0x0307: return "intel_core_ultra9";
		default: return processor_family_to_string(v & 0xFF);
	}
}

static const char *processor_upgrade_to_string(int v) {
	switch (v) {
		case 0x01: return "other";
		case 0x02: return "unknown";
		case 0x03: return "daughter_board";
		case 0x04: return "zif_socket";
		case 0x05: return "piggy_back";
		case 0x06: return "none";
		case 0x07: return "lif_socket";
		case 0x08: return "slot1";
		case 0x09: return "slot2";
		case 0x0A: return "370_pin_socket";
		case 0x0B: return "SlotA";
		case 0x0C: return "SlotM";
		case 0x0D: return "Socket423";
		case 0x0E: return "SocketA";
		case 0x0F: return "Socket478";
		case 0x10: return "Socket754";
		case 0x11: return "Socket940";
		case 0x12: return "Socket939";
		case 0x13: return "mPGA604";
		case 0x14: return "LGA771";
		case 0x15: return "LGA775";
		case 0x16: return "S1";
		case 0x17: return "AM2";
		case 0x18: return "F1207";
		case 0x19: return "LGA1366";
		case 0x1A: return "G34";
		case 0x1B: return "AM3";
		case 0x1C: return "C32";
		case 0x1D: return "LGA1156";
		case 0x1E: return "LGA1567";
		case 0x1F: return "PGA988A";
		case 0x20: return "BGA1288";
		case 0x21: return "rPGA988B";
		case 0x22: return "BGA1023";
		case 0x23: return "BGA1224";
		case 0x24: return "LGA1155";
		case 0x25: return "LGA1356";
		case 0x26: return "LGA2011";
		case 0x27: return "FS1";
		case 0x28: return "FS2";
		case 0x29: return "FM1";
		case 0x2A: return "FM2";
		case 0x2B: return "LGA2011_3";
		case 0x2C: return "LGA1356_3";
		case 0x2D: return "LGA1150";
		case 0x2E: return "BGA1168";
		case 0x2F: return "BGA1234";
		case 0x30: return "BGA1364";
		case 0x31: return "AM4";
		case 0x32: return "LGA1151";
		case 0x33: return "BGA1356";
		case 0x34: return "BGA1440";
		case 0x35: return "BGA1515";
		case 0x36: return "LGA3647_1";
		case 0x37: return "SP3";
		case 0x38: return "SP3r2";
		case 0x39: return "LGA2066";
		case 0x3A: return "BGA1392";
		case 0x3B: return "BGA1510";
		case 0x3C: return "BGA1528";
		case 0x3D: return "LGA4189";
		case 0x3E: return "LGA1200";
		case 0x3F: return "LGA4677";
		case 0x40: return "LGA1700";
		case 0x41: return "BGA1744";
		case 0x42: return "BGA1781";
		case 0x43: return "BGA1211";
		case 0x44: return "BGA2422";
		case 0x45: return "LGA1211";
		case 0x46: return "LGA2422";
		case 0x47: return "LGA5773";
		case 0x48: return "BGA5773";
		case 0x49: return "AM5";
		case 0x4A: return "SP5";
		case 0x4B: return "SP6";
		case 0x4C: return "BGA883";
		case 0x4D: return "BGA1190";
		case 0x4E: return "BGA4129";
		case 0x4F: return "LGA4710";
		case 0x50: return "LGA7529";
		case 0x51: return "BGA1964";
		case 0x52: return "BGA1792";
		case 0x53: return "BGA2049";
		case 0x54: return "BGA2551";
		case 0x55: return "LGA1851";
		case 0x56: return "BGA2114";
		case 0x57: return "BGA2833";
		default: return "invalid";
	}
}

static void set_processor_feature_flags(confignode *m, PROCESSOR_FEATURE_FLAGS *f) {
	confignode *fm = confignode_new_map();
	confignode_path_map_set(m, "features", fm);
	confignode_path_set_bool(fm, "fpu", f->ProcessorFpu);
	confignode_path_set_bool(fm, "vme", f->ProcessorVme);
	confignode_path_set_bool(fm, "de", f->ProcessorDe);
	confignode_path_set_bool(fm, "pse", f->ProcessorPse);
	confignode_path_set_bool(fm, "tsc", f->ProcessorTsc);
	confignode_path_set_bool(fm, "msr", f->ProcessorMsr);
	confignode_path_set_bool(fm, "pae", f->ProcessorPae);
	confignode_path_set_bool(fm, "mce", f->ProcessorMce);
	confignode_path_set_bool(fm, "cx8", f->ProcessorCx8);
	confignode_path_set_bool(fm, "apic", f->ProcessorApic);
}

static void set_processor_characteristics(confignode *m, PROCESSOR_CHARACTERISTIC_FLAGS *c) {
	confignode *cm = confignode_new_map();
	confignode_path_map_set(m, "characteristics", cm);
	confignode_path_set_bool(cm, "unknown", c->ProcessorUnknown);
	confignode_path_set_bool(cm, "64bit_capable", c->Processor64BitCapable);
	confignode_path_set_bool(cm, "multi_core", c->ProcessorMultiCore);
	confignode_path_set_bool(cm, "hardware_thread", c->ProcessorHardwareThread);
	confignode_path_set_bool(cm, "execute_protection", c->ProcessorExecuteProtection);
	confignode_path_set_bool(cm, "enhanced_virtualization", c->ProcessorEnhancedVirtualization);
	confignode_path_set_bool(cm, "power_performance_ctrl", c->ProcessorPowerPerformanceCtrl);
	confignode_path_set_bool(cm, "128bit_capable", c->Processor128BitCapable);
	confignode_path_set_bool(cm, "arm64_soc_id", c->ProcessorArm64SocId);
}

void smbios_load_type4(embloader_smbios *ctx, confignode *m, SMBIOS_STRUCTURE_POINTER ptr) {
	SMBIOS_TABLE_TYPE4 *t = ptr.Type4;
	embloader_smbios_set_config_string(ctx, ptr, m, "socket", t->Socket);
	embloader_smbios_set_config_string(ctx, ptr, m, "manufacturer", t->ProcessorManufacturer);
	embloader_smbios_set_config_string(ctx, ptr, m, "version", t->ProcessorVersion);
	embloader_smbios_set_config_string(ctx, ptr, m, "serial_number", t->SerialNumber);
	embloader_smbios_set_config_string(ctx, ptr, m, "asset_tag", t->AssetTag);
	embloader_smbios_set_config_string(ctx, ptr, m, "part_number", t->PartNumber);
	confignode_path_set_string(m, "type", processor_type_to_string(t->ProcessorType));
	if (t->ProcessorFamily == 0xfe && ctx->version >= SMBIOS_VER(2,6)) {
		confignode_path_set_string(m, "family", processor_family2_to_string(t->ProcessorFamily2));
	} else {
		confignode_path_set_string(m, "family", processor_family_to_string(t->ProcessorFamily));
	}
	confignode_path_set_int(m, "external_clock", t->ExternalClock);
	confignode_path_set_int(m, "max_speed", t->MaxSpeed);
	confignode_path_set_int(m, "current_speed", t->CurrentSpeed);
	confignode_path_set_int(m, "status", t->Status);
	confignode_path_set_string(m, "processor_upgrade", processor_upgrade_to_string(t->ProcessorUpgrade));
	confignode_path_set_int(m, "l1_cache_handle", t->L1CacheHandle);
	confignode_path_set_int(m, "l2_cache_handle", t->L2CacheHandle);
	confignode_path_set_int(m, "l3_cache_handle", t->L3CacheHandle);
	if (ctx->version >= SMBIOS_VER(2,5)) {
		confignode_path_set_int(m, "core_count", t->CoreCount);
		confignode_path_set_int(m, "enabled_core_count", t->EnabledCoreCount);
		confignode_path_set_int(m, "thread_count", t->ThreadCount);
		set_processor_characteristics(m, (PROCESSOR_CHARACTERISTIC_FLAGS*)&t->ProcessorCharacteristics);
	}
	set_processor_feature_flags(m, &t->ProcessorId.FeatureFlags);
	if (ctx->version >= SMBIOS_VER(3,0)) {
		int core_count = (t->CoreCount == 0xFF) ? t->CoreCount2 : t->CoreCount;
		int enabled_core_count = (t->EnabledCoreCount == 0xFF) ? t->EnabledCoreCount2 : t->EnabledCoreCount;
		int thread_count = (t->ThreadCount == 0xFF) ? t->ThreadCount2 : t->ThreadCount;
		confignode_path_set_int(m, "core_count", core_count);
		confignode_path_set_int(m, "enabled_core_count", enabled_core_count);
		confignode_path_set_int(m, "thread_count", thread_count);
	} else {
		confignode_path_set_int(m, "core_count", t->CoreCount);
		confignode_path_set_int(m, "enabled_core_count", t->EnabledCoreCount);
		confignode_path_set_int(m, "thread_count", t->ThreadCount);
	}
	if (ctx->version >= SMBIOS_VER(3,6)) {
		confignode_path_set_int(m, "thread_enabled", t->ThreadEnabled);
	}
	if (ctx->version >= SMBIOS_VER(3,8)) {
		embloader_smbios_set_config_string(ctx, ptr, m, "socket_type", t->SocketType);
	}
}
