#include "../smbios.h"

void smbios_load_type0(embloader_smbios *ctx, confignode *m, SMBIOS_STRUCTURE_POINTER ptr) {
	SMBIOS_TABLE_TYPE0 *t = ptr.Type0;
	embloader_smbios_set_config_string(ctx, ptr, m, "vendor", t->Vendor);
	embloader_smbios_set_config_string(ctx, ptr, m, "version", t->BiosVersion);
	embloader_smbios_set_config_string(ctx, ptr, m, "release_date", t->BiosReleaseDate);
	confignode_path_set_int(m, "segment", t->BiosSegment);
	confignode_path_set_int(m, "size", t->BiosSize);
	confignode_path_set_int(m, "major", t->SystemBiosMajorRelease);
	confignode_path_set_int(m, "minor", t->SystemBiosMinorRelease);
	confignode_path_set_int(m, "ec_major", t->EmbeddedControllerFirmwareMajorRelease);
	confignode_path_set_int(m, "ec_minor", t->EmbeddedControllerFirmwareMinorRelease);
	confignode *cm = confignode_new_map();
	confignode_path_map_set(m, "characteristics", cm);
	MISC_BIOS_CHARACTERISTICS c = t->BiosCharacteristics;
	confignode_path_set_bool(cm, "bios_characteristics_not_supported", c.BiosCharacteristicsNotSupported);
	confignode_path_set_bool(cm, "isa_is_supported", c.IsaIsSupported);
	confignode_path_set_bool(cm, "mca_is_supported", c.McaIsSupported);
	confignode_path_set_bool(cm, "eisa_is_supported", c.EisaIsSupported);
	confignode_path_set_bool(cm, "pci_is_supported", c.PciIsSupported);
	confignode_path_set_bool(cm, "pcmcia_is_supported", c.PcmciaIsSupported);
	confignode_path_set_bool(cm, "plug_and_play_is_supported", c.PlugAndPlayIsSupported);
	confignode_path_set_bool(cm, "apm_is_supported", c.ApmIsSupported);
	confignode_path_set_bool(cm, "bios_is_upgradable", c.BiosIsUpgradable);
	confignode_path_set_bool(cm, "bios_shadowing_allowed", c.BiosShadowingAllowed);
	confignode_path_set_bool(cm, "vl_vesa_is_supported", c.VlVesaIsSupported);
	confignode_path_set_bool(cm, "escd_support_is_available", c.EscdSupportIsAvailable);
	confignode_path_set_bool(cm, "boot_from_cd_is_supported", c.BootFromCdIsSupported);
	confignode_path_set_bool(cm, "selectable_boot_is_supported", c.SelectableBootIsSupported);
	confignode_path_set_bool(cm, "rom_bios_is_socketed", c.RomBiosIsSocketed);
	confignode_path_set_bool(cm, "boot_from_pcmcia_is_supported", c.BootFromPcmciaIsSupported);
	confignode_path_set_bool(cm, "edd_specification_is_supported", c.EDDSpecificationIsSupported);
	confignode_path_set_bool(cm, "japanese_nec_floppy_is_supported", c.JapaneseNecFloppyIsSupported);
	confignode_path_set_bool(cm, "japanese_toshiba_floppy_is_supported", c.JapaneseToshibaFloppyIsSupported);
	confignode_path_set_bool(cm, "floppy525_360_is_supported", c.Floppy525_360IsSupported);
	confignode_path_set_bool(cm, "floppy525_12_is_supported", c.Floppy525_12IsSupported);
	confignode_path_set_bool(cm, "floppy35_720_is_supported", c.Floppy35_720IsSupported);
	confignode_path_set_bool(cm, "floppy35_288_is_supported", c.Floppy35_288IsSupported);
	confignode_path_set_bool(cm, "print_screen_is_supported", c.PrintScreenIsSupported);
	confignode_path_set_bool(cm, "keyboard8042_is_supported", c.Keyboard8042IsSupported);
	confignode_path_set_bool(cm, "serial_is_supported", c.SerialIsSupported);
	confignode_path_set_bool(cm, "printer_is_supported", c.PrinterIsSupported);
	confignode_path_set_bool(cm, "cga_mono_is_supported", c.CgaMonoIsSupported);
	confignode_path_set_bool(cm, "nec_pc98", c.NecPc98);
	MISC_BIOS_CHARACTERISTICS_EXTENSION *ce = (void*)t->BIOSCharacteristicsExtensionBytes;
	MBCE_BIOS_RESERVED cb = ce->BiosReserved;
	MBCE_SYSTEM_RESERVED cs = ce->SystemReserved;
	confignode_path_set_bool(cm, "acpi_is_supported", cb.AcpiIsSupported);
	confignode_path_set_bool(cm, "usb_legacy_is_supported", cb.UsbLegacyIsSupported);
	confignode_path_set_bool(cm, "agp_is_supported", cb.AgpIsSupported);
	confignode_path_set_bool(cm, "i2o_boot_is_supported", cb.I2OBootIsSupported);
	confignode_path_set_bool(cm, "ls120_boot_is_supported", cb.Ls120BootIsSupported);
	confignode_path_set_bool(cm, "atapi_zip_drive_boot_is_supported", cb.AtapiZipDriveBootIsSupported);
	confignode_path_set_bool(cm, "boot1394_is_supported", cb.Boot1394IsSupported);
	confignode_path_set_bool(cm, "smart_battery_is_supported", cb.SmartBatteryIsSupported);
	confignode_path_set_bool(cm, "bios_boot_spec_is_supported", cs.BiosBootSpecIsSupported);
	confignode_path_set_bool(cm, "function_key_network_boot_is_supported", cs.FunctionKeyNetworkBootIsSupported);
	confignode_path_set_bool(cm, "target_content_distribution_enabled", cs.TargetContentDistributionEnabled);
	confignode_path_set_bool(cm, "uefi_specification_supported", cs.UefiSpecificationSupported);
	confignode_path_set_bool(cm, "virtual_machine_supported", cs.VirtualMachineSupported);
	confignode_path_set_bool(cm, "manufacturing_mode_supported", cs.ManufacturingModeSupported);
	confignode_path_set_bool(cm, "manufacturing_mode_enabled", cs.ManufacturingModeEnabled);
}
