#define STB_C_LEXER_IMPLEMENTATION
#define STB_DIVIDE_IMPLEMENTATION
#define STB_DS_IMPLEMENTATION
#define STB_DXT_IMPLEMENTATION
#define STB_HEXWAVE_IMPLEMENTATION
#define STB_IMAGE_IMPLEMENTATION
#define STB_IMAGE_WRITE_IMPLEMENTATION
#define STB_INCLUDE_IMPLEMENTATION
#define STB_LEAKCHECK_IMPLEMENTATION
#define STB_PERLIN_IMPLEMENTATION
#define STB_RECT_PACK_IMPLEMENTATION
#define STB_SPRINTF_IMPLEMENTATION
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_c_lexer.h"
#include "stb_divide.h"
#include "stb_ds.h"
#include "stb_dxt.h"
#include "stb_easy_font.h"
#include "stb_hexwave.h"
#include "stb_image.h"
#include "stb_image_resize2.h"
#include "stb_image_write.h"
#include "stb_include.h"
#include "stb_leakcheck.h"
#include "stb_perlin.h"
#include "stb_rect_pack.h"
#include "stb_sprintf.h"
#include "stb_truetype.h"
#include "stb_vorbis.c"
